name: StagingDeploymentForAndroid
on:
  push:
    branches:
      - staging
      
jobs:
  build_android:
    environment: staging_env
    name: Build Flutter (Android-APK)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: staging
    - uses: subosito/flutter-action@v2.10.0
      with:
          flutter-version: '3.7.10'
          channel: 'stable'
    - run: flutter build apk --split-per-abi
      env:
        API_URL: ${{ secrets.API_URL }}
        USERNAME: ${{ secrets.SERVICE_USER }}
        PASSWORD: ${{ secrets.SERVICE_PASSWORD }}
    - uses: easingthemes/ssh-deploy@v4.1.8
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "build/app/outputs/apk/release/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
